services:
  auth-service:
    image: node:20-alpine
    container_name: auth-service
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "rm -rf node_modules package-lock.json && npm install && npm run build && npm run start"
    ports:
      - "6080:6080"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"