export const ENV = {
  SECRETS_ENDPOINT: 'SECRETS_ENDPOINT',
  AWS_REGION: 'AWS_REGION',
  AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY',
  PASETO_SECRET_NAME: 'PASETO_SECRET_NAME',
  PG_USER: 'PG_USER',
  PG_HOST: 'PG_HOST',
  PG_DATABASE: 'PG_DATABASE',
  PG_PASSWORD: 'PG_PASSWORD',
  PG_PORT: 'PG_PORT',
  SUPER_SECRET_KEY: 'SUPER_SECRET_KEY',
};

export const REQUIRED_ENV_VARS = Object.values(ENV);