export const TYPES = {
  CreateUserUseCase: Symbol.for('CreateUserUseCase'),
  LoginUseCase: Symbol.for('LoginUseCase'),
  GetPayloadUseCase: Symbol.for('GetPayloadUseCase'),
  VerificateSecretKeyUseCase: Symbol.for('VerificateSecretKeyUseCase'),
  AuthService: Symbol.for('AuthService'),
  UserRepository: Symbol.for('UserRepository'),
  RefreshTokenRepository: Symbol.for('RefreshTokenRepository'),
  RefreshTokenUseCase: Symbol.for('RefreshTokenUseCase'),
  SuperUserController: Symbol.for('SuperUserController'),
  AuthController: Symbol.for('AuthController'),
  MfaLoginService: Symbol.for('MfaLoginService'),
  MfaFactorsRepository: Symbol.for('MfaFactorsRepository'),
  RecoveryCodesRepository: Symbol.for('RecoveryCodesRepository'),
  IssueTokensForUserIdUseCase: Symbol.for('IssueTokensForUserIdUseCase'),
  MfaTotpService: Symbol.for('MfaTotpService'),
  PasswordHasher: Symbol.for('PasswordHasher'),
};